version: "3"
services:
  flask:
    container_name: Health_flask
    build: app/
    restart: always
    ports:
      - 5500:5000
    volumes:
      - ./app:/app
    working_dir: /app
    command: python3 app.py
    environment:
      - TZ=Asia/Tokyo

  php:
    container_name: Health_php
    image: php:8.2-apache
    ports:
      - 8500:80
    volumes:
      - ./php/doc:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - TZ=Asia/Tokyo
  
  cloudflared:
    image: cloudflare/cloudflared
    container_name: Health_cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}