version: "3"
services:
  flask:
    container_name: Health_flask
    build: app/
    restart: always
    ports:
      - 5500:5000
    volumes:
      - ./app:/app
    working_dir: /app
    command: python3 app.py
    environment:
      - TZ=Asia/Tokyo

  php:
    container_name: php
    image: php:8.1-apache
    volumes:
      - ./php/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8080:80
    environment:
      - TZ=Asia/Tokyo